version: 3.3.1.{build}
os: Visual Studio 2015
test: off
build_script:
- cmd: build.cmd ci
artifacts:
  - path: './bin/unity/*.unitypackage'
    name: UnityPackage
cache:
- packages -> **\packages.config
